name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Install pipreqs
        run: |
          . venv/bin/activate
          pip install pipreqs

      - name: Generate requirements file with pipreqs
        run: |
          . venv/bin/activate
          pipreqs . --force  # Regenerate the requirements file

      - name: Check for unused dependencies
        run: |
          . venv/bin/activate
          pipreqs --dry-run .  # Check for unused dependencies

      - name: Install black
        run: |
          . venv/bin/activate
          pip install black

      - name: Run black (check only)
        run: |
          . venv/bin/activate
          black --check .  # This checks for code style issues without applying any fixes
        continue-on-error: true  # Continue even if black finds formatting issues

